name: mobilelogger
description: "Flutter front end for LubeLogger"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter # Required for any Flutter project
  http: ^0.13.3 # Used for making HTTP requests
  uuid: ^3.0.4 # Used for generating unique identifiers
  sqflite: ^2.0.0+4 # Used for SQLite database operations
  path: ^1.8.0 # Used for manipulating file paths
  intl: ^0.18.0 # Used for formatting dates

dev_dependencies:
  flutter_test:
    sdk: flutter # Required for testing Flutter applications
  flutter_lints: ^5.0.0 # Provides linting rules for Flutter projects
  flutter_launcher_icons: "^0.14.3" # Used for generating app icons

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21